version: '3.8'
services:
  api:
    build: .
    container_name: nestjs-api
    restart: always
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_management
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_management
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
